# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.4.8
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      chromium \
      git \
      libpq-dev \
      libvips \
      libyaml-dev \
      postgresql-client \
      pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3

COPY Gemfile Gemfile.lock ./
RUN bundle install && gem install foreman --no-document

COPY . .

EXPOSE 3000

CMD ["./bin/dev"]
